# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('reference', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('preu', models.IntegerField(null=True)),
                ('descripcio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitiy', models.IntegerField(null=True)),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugshop.Product')),
            ],
        ),
    ]
