# Generated by Django 2.2 on 2019-05-12 18:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('reference', models.BigIntegerField(default='', primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('price', models.FloatField(null=True)),
                ('discount', models.FloatField(default=0, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(default='images/None/no-img.jpg', null=True, upload_to='images/')),
                ('register_time', models.DateTimeField(auto_now=True)),
                ('buy', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitiy', models.IntegerField(null=True)),
                ('key', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='drugshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('product', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='drugshop.product')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
