# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adressa_fisica', models.TextField()),
                ('telefon', models.IntegerField()),
                ('numero_compte', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugshop.product'),
        ),
        migrations.AddField(
            model_name='carret',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugshop.customer'),
        ),
        migrations.AddField(
            model_name='carret',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugshop.product'),
        ),
    ]
